// File generated by Antigravity.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
      case TargetPlatform.windows:
      case TargetPlatform.linux:
        return web;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuj8KP0FNMsHX9JXS_bqCn7as2BOhLSdk',
    appId: '1:1059364112756:web:09dd725b67cc2e78938421',
    messagingSenderId: '1059364112756',
    projectId: 'attendance-app-38291',
    authDomain: 'attendance-app-38291.firebaseapp.com',
    storageBucket: 'attendance-app-38291.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8uJoZaYFs7DrMViSYqfQzOwjvuG1W_sU',
    appId: '1:1059364112756:android:09fa16cab48898f2938421',
    messagingSenderId: '1059364112756',
    projectId: 'attendance-app-38291',
    storageBucket: 'attendance-app-38291.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdoVU2cBhNn0RkmvD3JQItwrnQSD0E5mk',
    appId: '1:1059364112756:ios:a399a4b872f0d071938421',
    messagingSenderId: '1059364112756',
    projectId: 'attendance-app-38291',
    storageBucket: 'attendance-app-38291.firebasestorage.app',
    iosBundleId: 'com.attendance.attendanceApp',
  );
}
